const translations = {
    fr: {
        // Nav
        "nav.home": "Page d'accueil",
        "nav.photos": "Projets photos",
        "nav.projets": "Projets",
        "nav.parcours": "Parcours",
        "nav.contact": "Contact",

        // Home hero
        "home.hero.title": "Nicolas Didier",
        "home.hero.subtitle": "Photographe & Animateur",
        "home.hero.badge": "Actuellement à Vilnius, Lituanie",
        "home.hero.scroll": "Défiler",
        "home.hero.cta1": "Voir mes photos",
        "home.hero.cta2": "Mon parcours",

        // Home highlights
        "home.highlights.title": "Ce que je fais",
        "home.highlights.subtitle": "Photographie, animation culturelle et coopération internationale",
        "home.highlights.photo.title": "Photographie",
        "home.highlights.photo.desc": "Capturer des moments authentiques — nature, portraits et paysages urbains à travers le monde.",
        "home.highlights.anim.title": "Projets",
        "home.highlights.anim.desc": "Développement d'applications web, communication visuelle et animation d'ateliers collaboratifs.",
        "home.highlights.intl.title": "Relations Internationales",
        "home.highlights.intl.desc": "Expérience au Japon, en France et en Lituanie — projets de coopération et échanges interculturels.",
        "home.highlights.discover": "Découvrir →",

        // Home stats
        "home.stats.countries": "Pays d'expérience",
        "home.stats.languages": "Langues parlées",
        "home.stats.experience": "Ans d'expérience pro",
        "home.stats.degree": "Sciences Po",

        // Footer
        "footer.contact": "Contact",
        "footer.email": "Me contacter",
        "footer.social": "Réseaux Sociaux",


        // Photos
        "photos.filters.all": "Tout",
        "photos.filters.nature": "Nature",
        "photos.filters.urbain": "Urbain",
        "photos.filters.portrait": "Portrait",
        "photos.filters.paysage": "Paysage",
        "photos.filters.divers": "Divers",

        // Contact
        "contact.title": "Contact",
        "contact.intro": "Vous souhaitez collaborer sur un projet ou simplement dire bonjour ? N'hésitez pas à me contacter !",
        "contact.send_email": "Envoyer un e-mail",
        "contact.available": "Disponible pour projets & collaborations",
        "contact.linkedin_desc": "Mon profil professionnel",
        "contact.extra": "📍 Basé à Vilnius, Lituanie — disponible à l'international",

        // Projets
        "projets.title": "Mes Projets",
        "projets.subtitle": "Recherche, création visuelle, développement web et animation — découvrez mes réalisations.",
        "projets.details": "Détails",
        "projets.tab.research": "Recherche",
        "projets.tab.visual": "Projets Visuels",
        "projets.tab.web": "Web / Coding",
        "projets.tab.animation": "Animation / Facilitation",
        "projets.research.title": "Travaux de Recherche",
        "projets.research.desc": "Mémoires, analyses géopolitiques et travaux académiques réalisés durant mon parcours en relations internationales.",
        "projets.visual.title": "Projets Visuels",
        "projets.visual.desc": "Communication visuelle, gestion de réseaux sociaux, photographie événementielle et création de contenus.",
        "projets.web.title": "Projets Web / Coding",
        "projets.web.desc": "Développement de sites web, applications et outils numériques.",
        "projets.anim.title": "Animation & Facilitation",
        "projets.anim.desc": "Ateliers interactifs, facilitation de débats et animation culturelle.",
        "projets.r1.title": "Mémoire de Master — Études Européennes et Internationales",
        "projets.r1.desc": "Recherche approfondie dans le cadre du Master en études européennes et internationales.",
        "projets.r2.title": "Travaux de recherche LEA — Anglais-Japonais",
        "projets.r2.desc": "Travaux de recherche en langues étrangères appliquées avec une spécialisation en communication interculturelle.",
        "projets.r3.date": "2024",
        "projets.r3.title": "Analyse des enjeux de l'Intelligence Artificielle en Chine",
        "projets.r3.org": "Institut d'Études Politiques",
        "projets.r3.desc": "Ce travail examine comment la Chine utilise l'intelligence artificielle comme un levier de puissance totale. L'étude montre que l'IA est au cœur de la stratégie économique chinoise, de sa modernisation militaire et de son modèle de contrôle social. Le rapport analyse également les réactions des puissances concurrentes (USA et Europe).",
        "projets.r4.date": "2024",
        "projets.r4.title": "Étude sur l'internationalisation de l'histoire globale au Japon",
        "projets.r4.org": "Institut d'Études Politiques",
        "projets.r4.desc": "Ce projet explore comment le concept d'« histoire globale » a été adapté au contexte académique japonais. L'étude met en lumière des approches innovantes comme la Kaiiki-shi (histoire maritime), qui propose une vision du monde centrée sur les échanges maritimes plutôt que sur une narration purement occidentale ou centrée sur les États-nations.",
        "projets.r5.date": "2024",
        "projets.r5.title": "Système de redistribution dans les monarchies du Golfe",
        "projets.r5.org": "Institut d'Études Politiques",
        "projets.r5.desc": "Cette analyse porte sur la manière dont les pays riches en pétrole (comme l'Arabie Saoudite ou le Qatar) gèrent et redistribuent leur richesse. Le projet retrace l'évolution de ces mécanismes depuis les crises pétrolières de 1973 et examine les défis actuels, notamment la gestion d'un marché du travail divisé entre citoyens nationaux et travailleurs expatriés.",
        "projets.r6.date": "2025",
        "projets.r6.title": "Mémoire de Master — Présence française et réseaux en Asie du Sud-Est",
        "projets.r6.org": "Institut d'Études Politiques",
        "projets.r6.desc": "Ce travail de recherche approfondi explore comment la présence française (réseaux d'affaires, diplomatiques, éducatifs et culturels) participe au développement ou à la transformation des réseaux entre la France et les pays d'Asie du Sud-Est. L'étude analyse comment ces acteurs créent des ponts entre les économies et les cultures, transformant les héritages historiques en partenariats modernes.",
        "projets.r7.date": "2024",
        "projets.r7.title": "La cérémonie de la frontière d'Attari-Wagah et les relations indo-pakistanaises",
        "projets.r7.org": "Institut d'Études Politiques",
        "projets.r7.desc": "Ce mémoire étudie la relation paradoxale entre l'Inde et le Pakistan à travers la cérémonie militaire quotidienne de la frontière d'Attari-Wagah. Entre chorégraphies agressives et coopération logistique parfaite, ce rituel devient une métaphore des tensions géopolitiques, des rivalités religieuses et de l'héritage traumatique de la Partition de 1947. L'analyse démontre comment cette mise en scène spectaculaire permet aux deux nations d'exprimer leur identité nationale et leurs différends, tout en maintenant un espace de dialogue et de coexistence fragile.",
        "projets.download": "Lire le rapport (PDF)",
        "projets.instagram": "Voir sur Instagram",
        "projets.website": "Voir le site officiel",
        "projets.w1.title": "Portfolio Personnel",
        "projets.w1.org": "Projet personnel",
        "projets.w1.desc": "Conception et développement de ce site portfolio avec un design premium dark theme, gestion de photos via Firebase et support bilingue FR/EN.",
        "projets.w2.title": "Plateforme Indopacifique",
        "projets.w2.org": "Projet académique",
        "projets.w2.desc": "Développement d'un portail web éducatif sur la zone indopacifique.",
        "projets.github": "Voir sur GitHub",
        "projets.w3.title": "Apprentissage du Lituanien",
        "projets.w3.org": "Projet personnel",
        "projets.w3.desc": "Application web interactive pour l'apprentissage du lituanien (niveaux A1, A2, B1) avec des leçons de grammaire, exercices d'entraînement et dictionnaire de flashcards.",
        "projets.w4.title": "Préparation aux Concours du MEAE — Zone Indopacifique",
        "projets.w4.org": "Projet personnel",
        "projets.w4.desc": "Portail web interactif conçu pour accompagner la préparation aux concours du Ministère de l'Europe et des Affaires Étrangères (MEAE), centré sur les enjeux géopolitiques et stratégiques de la zone Indopacifique.",
        "projets.w5.title": "N1 Benkyo Hub — Application d'étude JLPT N1",
        "projets.w5.org": "Projet personnel",
        "projets.w5.desc": "Application mobile d'apprentissage hors-ligne pour la préparation au niveau JLPT N1 du japonais, proposant plus de 1900 kanjis, 2300 mots de vocabulaire et fiches de grammaire avec synthèse vocale.",
        "projets.w6.title": "Magiška Abėcėlė — Alphabet Français pour Lituaniens",
        "projets.w6.org": "Institut français de Lituanie",
        "projets.w6.desc": "Application d'apprentissage de l'alphabet français conçue pour les apprenants lituaniens, s'appuyant sur des mots transparents et des prononciations audio interactives.",
        "projets.w7.title": "Échanges Scolaires France-Lituanie",
        "projets.w7.org": "Institut français de Lituanie",
        "projets.w7.desc": "Plateforme collaborative sur les échanges scolaires et partenariats éducatifs entre la France et la Lituanie, comprenant un guide pour les enseignants et une carte interactive des régions.",
        "projets.w8.title": "Créateur de Cartes Time's Up Français-Lituanien",
        "projets.w8.org": "Institut français de Lituanie",
        "projets.w8.desc": "Générateur de cartes de jeu bilingues français-lituanien pour le jeu Time's Up, développé pour animer des ateliers linguistiques et culturels.",
        "projets.w3.detail1": "Sélection de leçons interactives adaptées aux niveaux A1, A2 et B1.",
        "projets.w3.detail2": "Exercices interactifs pour s'entraîner à la grammaire et à la conjugaison.",
        "projets.w3.detail3": "Dictionnaire intégré avec système de flashcards pour l'apprentissage du vocabulaire.",
        "projets.w4.detail1": "Fiches de révision géopolitiques détaillées par pays de la zone Indopacifique.",
        "projets.w4.detail2": "Glossaire exhaustif des termes diplomatiques et relations internationales.",
        "projets.w4.detail3": "Archives de sujets d'annales et modules d'entraînement pour les concours.",
        "projets.w5.detail1": "Base de données locale de 1949 Kanjis, 2329 mots de vocabulaire et 218 règles de grammaire.",
        "projets.w5.detail2": "Synthèse vocale intégrée pour écouter la prononciation des mots.",
        "projets.w5.detail3": "Suivi de progression de l'apprentissage avec dashboard statistique.",
        "projets.w5.detail4": "Planificateur d'étude quotidien et quiz d'entraînement.",
        "projets.w6.detail1": "Grille interactive de l'alphabet avec prononciations sonores.",
        "projets.w6.detail2": "Association avec des mots transparents (proches en français et en lituanien).",
        "projets.w6.detail3": "Conçu pour l'introduction à la langue française à l'Institut Français.",
        "projets.w7.detail1": "Carte interactive des régions et établissements partenaires.",
        "projets.w7.detail2": "Ressources téléchargeables et guides d'accompagnement pour les professeurs.",
        "projets.w7.detail3": "Espace de partage pour valoriser les projets scolaires bilatéraux.",
        "projets.w8.detail1": "Génération dynamique de cartes de jeu bilingues français-lituanien.",
        "projets.w8.detail2": "Interface épurée et optimisée pour l'impression recto/verso des cartes.",
        "projets.w8.detail3": "Règles du jeu consultables et imprimables directement depuis la plateforme.",

        "projets.v1.title": "Communication & Création Visuelle",
        "projets.v1.org": "Institut français de Lituanie",
        "projets.v1.desc": "Conception graphique et création de contenus visuels de communication pour les réseaux sociaux et les événements de l'Institut français de Lituanie.",
        "projets.v1.detail1": "Visuels sur les réseaux sociaux autour de l'exposition « Écrire en Français ».",
        "projets.v1.detail2": "Visuels sur les réseaux sociaux autour des ateliers « Jeux de Société ».",
        "projets.v1.detail3": "Éléments visuels pour la promotion de la « Semaine du Cinéma Francophone ».",
        "projets.v1.link1": "Expo « Écrire en Français »",
        "projets.v1.link2": "Soirées Jeux de Société",

        "projets.a1.title": "Facilitation de la Fresque du Climat",
        "projets.a1.org": "Engagement Citoyen & Environnemental",
        "projets.a1.desc": "Animation d'ateliers d'intelligence collective pour sensibiliser les participants au dérèglement climatique, à ses causes et à ses conséquences systémiques.",
        "projets.a1.detail1": "Animation de sessions interactives et collaboratives basées sur les rapports du GIEC.",
        "projets.a1.detail2": "Facilitation de débats constructifs sur les actions individuelles et collectives à mener.",
        "projets.a1.detail3": "Adaptation du discours pour des publics variés d'étudiants et de citoyens.",
        "projets.a2.title": "Communication & Événementiel",
        "projets.a2.org": "Université Bordeaux Montaigne (Association LEA)",
        "projets.a2.desc": "Gestion de l'ensemble de la communication de l'association étudiante LEA afin d'améliorer l'engagement étudiant et de promouvoir les événements culturels.",
        "projets.a2.detail1": "Organisation d'événements culturels, de conférences et de rencontres associatives.",
        "projets.a2.detail2": "Création de visuels et promotion active sur les différents réseaux sociaux.",
        "projets.a3.title": "Soirées Jeux de Société",
        "projets.a3.org": "Institut français de Lituanie",
        "projets.a3.desc": "Animation de plusieurs ateliers de jeux de société à l'Institut français de Lituanie, favorisant l'apprentissage ludique et les échanges conviviaux en français.",
        "projets.a3.detail1": "Sélection et présentation de jeux de société adaptés aux apprenants de français.",
        "projets.a3.detail2": "Explication des règles et facilitation des conversations en français.",
        "projets.a3.detail3": "Création d'un espace d'échange interculturel et convivial.",
        "projets.a4.title": "Sensibilisation & Promotion du Français",
        "projets.a4.org": "Établissements scolaires de Lituanie",
        "projets.a4.desc": "Introduction à la culture et à la langue française auprès d'élèves de 5ème année (CM1/CM2) dans plusieurs établissements lituaniens, avec pour objectif de susciter leur intérêt à choisir le français en LV2.",
        "projets.a4.detail1": "Création d'ateliers ludiques et interactifs d'initiation linguistique.",
        "projets.a4.detail2": "Présentation dynamique de la culture française et de ses traditions.",
        "projets.a4.detail3": "Sensibilisation active pour inciter au choix du français comme deuxième langue (LV2).",
        "projets.a5.title": "Convention Citoyenne Étudiante (CCE)",
        "projets.a5.org": "IEP de Fontainebleau / UPEC",
        "projets.a5.desc": "Facilitation de tables rondes et d'ateliers de co-construction citoyenne dans le cadre de la Convention Citoyenne Étudiante de l'UPEC à l'IEP de Fontainebleau.",
        "projets.a5.detail1": "Animation de débats de groupes sur des propositions de politiques publiques et de transition écologique.",
        "projets.a5.detail2": "Accompagnement des étudiants dans la rédaction de recommandations officielles.",
        "projets.a5.detail3": "Familiarisation avec les techniques de démocratie participative et de délibération collective.",
        "projets.a6.title": "Ateliers ODD & Solidarité Internationale",
        "projets.a6.org": "La DCC (ONG)",
        "projets.a6.desc": "Animation d'ateliers interactifs sur les Objectifs de Développement Durable (ODD) et la solidarité internationale lors de mon stage à la DCC.",
        "projets.a6.detail1": "Conception et animation d'ateliers de sensibilisation aux ODD et à l'interculturalité.",
        "projets.a6.detail2": "Accompagnement et formation des futurs volontaires sur les enjeux de solidarité internationale.",
        "projets.a6.detail3": "Sessions menées de manière bilingue en français et en anglais.",
        "projets.a7.title": "Ateliers Interculturels & d'Intégration",
        "projets.a7.org": "AFS Intercultural Programs",
        "projets.a7.desc": "Animation de nombreux ateliers d'apprentissage et d'interculturalité destinés aux élèves en échange scolaire international.",
        "projets.a7.detail1": "Préparation et animation de sessions d'orientation et de débriefing culturel.",
        "projets.a7.detail2": "Accompagnement à l'intégration des jeunes et gestion des situations de choc culturel.",
        "projets.a7.detail3": "Animations menées en français, anglais et observation/aide en japonais.",

        // Parcours
        "parcours.title": "Mon Parcours",
        "parcours.subtitle": "Passionné par les enjeux géopolitiques et les politiques publiques, je cherche à contribuer aux initiatives de projets français à l'international.",
        "parcours.map.title": "🌏 Mon parcours international",
        "parcours.map.france": "France — Études & Travail",
        "parcours.map.japan": "Japon — Échange & Stage",
        "parcours.map.lithuania": "Lituanie — Actuellement",
        "parcours.tab.exp": "Expériences",
        "parcours.tab.edu": "Formation",
        "parcours.tab.skills": "Compétences",
        "parcours.tab.lang": "Langues",
        "parcours.exp.heading": "Expériences Professionnelles",
        "parcours.exp1.date": "Janvier 2026 — Présent",
        "parcours.exp1.title": "Volontaire pour la Coopération Éducative et Linguistique",
        "parcours.exp1.org": "Institut français de Lituanie",
        "parcours.exp1.d1": "Participation à l'animation d'ateliers éducatifs, culturels et citoyens",
        "parcours.exp1.d2": "Création de supports visuels et rédaction de contenus attractifs pour les réseaux sociaux",
        "parcours.exp1.d3": "Animation d'ateliers de découverte du français et de la culture francophone",
        "parcours.exp1.d4": "Conception d'activités ludiques alliant technologie et innovations autour de la culture française",
        "parcours.exp2.date": "Mai 2025 — Octobre 2025",
        "parcours.exp2.title": "Assistant Solidarité Internationale",
        "parcours.exp2.org": "La DCC (ONG)",
        "parcours.exp2.d1": "Gestion des candidatures France Volontaires pour des volontariats de solidarité internationale en réciprocité",
        "parcours.exp2.d2": "Gestion de notes de frais",
        "parcours.exp2.d3": "Organisation d'orientations et ateliers en lien avec l'AFD",
        "parcours.exp2.d4": "Suivi administratif des dossiers des volontaires (Visa, titre de séjour, assurance…)",
        "parcours.exp3.date": "Janvier 2024 — Janvier 2025",
        "parcours.exp3.title": "Assistant Programmes Internationaux",
        "parcours.exp3.d1": "Administration des transports (vols, trains), logistique",
        "parcours.exp3.d2": "Gestion de dossiers administratifs (visas, candidatures)",
        "parcours.exp3.d3": "Traduction anglais-français-japonais",
        "parcours.exp3.d4": "Gestion des réseaux sociaux (Meta, Instagram)",
        "parcours.edu.heading": "Formation Académique",
        "parcours.edu1.date": "Août 2023 — Novembre 2025",
        "parcours.edu1.title": "Master Études Européennes et Internationales",
        "parcours.edu1.org": "Institut d'Études Politiques",
        "parcours.edu1.desc": "Formation avancée en relations internationales, politique européenne et coopération internationale. Master entièrement en anglais.",
        "parcours.edu2.date": "Septembre 2020 — Juin 2023",
        "parcours.edu2.title": "Licence Langues Étrangères Appliquées",
        "parcours.edu2.org": "Université Bordeaux Montaigne",
        "parcours.edu2.desc": "Spécialisation Anglais-Japonais avec une composante forte en relations internationales et communication interculturelle.",
        "parcours.edu3.date": "Mars 2018 — Février 2019",
        "parcours.edu3.title": "Échange Lycéen — Programme AFS",
        "parcours.edu3.desc": "Année d'échange culturel et linguistique au Japon. Immersion complète dans la culture japonaise et apprentissage intensif de la langue.",
        "parcours.edu4.date": "Juin 2017 — Juillet 2020",
        "parcours.edu4.title": "Baccalauréat STI2D",
        "parcours.edu4.org": "Lycée Albert Claveille",
        "parcours.edu4.desc": "Sciences et Technologies de l'Industrie et du Développement Durable.",
        "parcours.skills.heading": "Compétences Techniques",
        "parcours.skill1.sub": "Suite bureautique complète",
        "parcours.skill4.sub": "Création & gestion de sites web",
        "parcours.skill5.sub": "Design graphique & réseaux sociaux",
        "parcours.skill6.sub": "Montage vidéo & édition",
        "parcours.interests.heading": "Centres d'Intérêt",
        "parcours.int1": "Informatique",
        "parcours.int2": "Badminton",
        "parcours.int3": "Photographie",
        "parcours.int4": "Géopolitique",
        "parcours.lang.heading": "Compétences Linguistiques",
        "parcours.lang1.name": "Français",
        "parcours.lang1.level": "Langue maternelle",
        "parcours.lang1.label": "Natif",
        "parcours.lang2.name": "Anglais",
        "parcours.lang2.level": "Compétence professionnelle",
        "parcours.lang2.label": "C1 avancé — Master en anglais",
        "parcours.lang3.name": "Japonais",
        "parcours.lang3.level": "Compétence professionnelle",

        // Admin
        "admin.title": "Tableau de Bord Admin"
    },
    en: {
        // Nav
        "nav.home": "Home",
        "nav.photos": "Photo Projects",
        "nav.projets": "Projects",
        "nav.parcours": "Journey",
        "nav.contact": "Contact",

        // Home hero
        "home.hero.title": "Nicolas Didier",
        "home.hero.subtitle": "Photographer & Animator",
        "home.hero.badge": "Currently in Vilnius, Lithuania",
        "home.hero.scroll": "Scroll",
        "home.hero.cta1": "See my photos",
        "home.hero.cta2": "My journey",

        // Home highlights
        "home.highlights.title": "What I Do",
        "home.highlights.subtitle": "Photography, cultural animation and international cooperation",
        "home.highlights.photo.title": "Photography",
        "home.highlights.photo.desc": "Capturing authentic moments — nature, portraits and urban landscapes across the world.",
        "home.highlights.anim.title": "Projects",
        "home.highlights.anim.desc": "Web application development, visual communication, and collaborative workshop animation.",
        "home.highlights.intl.title": "International Relations",
        "home.highlights.intl.desc": "Experience in Japan, France and Lithuania — cooperation projects and intercultural exchanges.",
        "home.highlights.discover": "Discover →",

        // Home stats
        "home.stats.countries": "Countries of experience",
        "home.stats.languages": "Languages spoken",
        "home.stats.experience": "Years professional exp.",
        "home.stats.degree": "Sciences Po",

        // Footer
        "footer.contact": "Contact",
        "footer.email": "Email me",
        "footer.social": "Socials",


        // Photos
        "photos.filters.all": "All",
        "photos.filters.nature": "Nature",
        "photos.filters.urbain": "Urban",
        "photos.filters.portrait": "Portrait",
        "photos.filters.paysage": "Landscape",
        "photos.filters.divers": "Various",

        // Contact
        "contact.title": "Contact",
        "contact.intro": "Interested in collaborating or just want to say hi? Don't hesitate to reach out!",
        "contact.send_email": "Send me an email",
        "contact.available": "Available for projects & collaborations",
        "contact.linkedin_desc": "My professional profile",
        "contact.extra": "📍 Based in Vilnius, Lithuania — available internationally",

        // Projects
        "projets.title": "My Projects",
        "projets.subtitle": "Research, visual creation, web development and facilitation — discover my work.",
        "projets.details": "Details",
        "projets.tab.research": "Research",
        "projets.tab.visual": "Visual Projects",
        "projets.tab.web": "Web / Coding",
        "projets.tab.animation": "Animation / Facilitation",
        "projets.research.title": "Research Work",
        "projets.research.desc": "Dissertations, geopolitical analyses and academic work completed during my international relations studies.",
        "projets.visual.title": "Visual Projects",
        "projets.visual.desc": "Visual communication, social media management, event photography and content creation.",
        "projets.web.title": "Web / Coding Projects",
        "projets.web.desc": "Website development, applications and digital tools.",
        "projets.anim.title": "Animation & Facilitation",
        "projets.anim.desc": "Interactive workshops, debate facilitation and cultural animation.",
        "projets.r1.title": "Master's Thesis — European and International Studies",
        "projets.r1.desc": "In-depth research as part of the Master's in European and International Studies.",
        "projets.r2.title": "Applied Languages Research — English-Japanese",
        "projets.r2.desc": "Research in applied foreign languages with a specialization in intercultural communication.",
        "projets.r3.date": "2024",
        "projets.r3.title": "Analysis of Artificial Intelligence Stakes in China",
        "projets.r3.org": "Institut d'Études Politiques",
        "projets.r3.desc": "This work examines how China uses artificial intelligence as a lever for total power. The study shows that AI is at the heart of China's economic strategy, military modernization, and social control model. The report also analyzes the reactions of competing powers (USA and Europe).",
        "projets.r4.date": "2024",
        "projets.r4.title": "Study on the Internationalization of Global History in Japan",
        "projets.r4.org": "Institut d'Études Politiques",
        "projets.r4.desc": "This project explores how the concept of 'global history' has been adapted to the Japanese academic context. The study highlights innovative approaches such as Kaiiki-shi (maritime history), which proposes a world view centered on maritime exchanges rather than a purely Western or nation-state-centric narrative.",
        "projets.r5.date": "2024",
        "projets.r5.title": "Redistribution System in the Gulf Monarchies",
        "projets.r5.org": "Institut d'Études Politiques",
        "projets.r5.desc": "This analysis focuses on how oil-rich countries (such as Saudi Arabia or Qatar) manage and redistribute their wealth. The project traces the evolution of these mechanisms since the 1973 oil crises and examines current challenges, particularly the management of a labor market split between national citizens and expatriate workers.",
        "projets.r6.date": "2025",
        "projets.r6.title": "Master's Thesis — French Presence and Networks in Southeast Asia",
        "projets.r6.org": "Institut d'Études Politiques",
        "projets.r6.desc": "This in-depth research work explores how the French presence (business, diplomatic, educational, and cultural networks) participates in the development or transformation of networks between France and Southeast Asian countries. The study analyzes how these actors build bridges between economies and cultures, transforming historical legacies into modern partnerships.",
        "projets.r7.date": "2024",
        "projets.r7.title": "The Attari-Wagah Border Ceremony and Indo-Pakistani Relations",
        "projets.r7.org": "Institut d'Études Politiques",
        "projets.r7.desc": "This thesis studies the paradoxical relationship between India and Pakistan through the daily military ceremony at the Attari-Wagah border. Between aggressive choreography and perfect logistical cooperation, this ritual becomes a metaphor for geopolitical tensions, religious rivalries, and the traumatic legacy of the 1947 Partition. The analysis demonstrates how this spectacular staging allows both nations to express their national identity and differences while maintaining a fragile space for dialogue and coexistence.",
        "projets.download": "Read the report (PDF)",
        "projets.instagram": "View on Instagram",
        "projets.website": "View official website",
        "projets.w1.title": "Personal Portfolio",
        "projets.w1.org": "Personal project",
        "projets.w1.desc": "Design and development of this portfolio website with premium dark theme, Firebase photo management and bilingual FR/EN support.",
        "projets.w2.title": "Indopacific Platform",
        "projets.w2.org": "Academic project",
        "projets.w2.desc": "Development of an educational web portal on the Indo-Pacific region.",
        "projets.github": "View on GitHub",
        "projets.w3.title": "Lithuanian Learning App",
        "projets.w3.org": "Personal project",
        "projets.w3.desc": "Interactive web application for learning Lithuanian (levels A1, A2, B1), featuring grammar lessons, training exercises, and a flashcard dictionary.",
        "projets.w4.title": "MEAE Exam Prep Portal — Indo-Pacific Region",
        "projets.w4.org": "Personal project",
        "projets.w4.desc": "Interactive web portal designed for preparing for the French Ministry for Europe and Foreign Affairs (MEAE) exams, focusing on Indo-Pacific geopolitical and strategic stakes.",
        "projets.w5.title": "N1 Benkyo Hub — JLPT N1 Study App",
        "projets.w5.org": "Personal project",
        "projets.w5.desc": "Mobile-friendly offline application for JLPT N1 Japanese exam preparation, containing 1,949 Kanji, 2,329 vocabulary words, and 218 grammar structures with text-to-speech.",
        "projets.w6.title": "Magiška Abėcėlė — French Alphabet for Lithuanians",
        "projets.w6.org": "French Institute of Lithuania",
        "projets.w6.desc": "French alphabet learning tool designed for Lithuanian speakers, utilizing transparent words and interactive audio pronunciations.",
        "projets.w7.title": "France-Lithuania School Exchanges",
        "projets.w7.org": "French Institute of Lithuania",
        "projets.w7.desc": "Collaborative web platform for school exchanges and educational partnerships between France and Lithuania, featuring a teachers' guide and interactive region map.",
        "projets.w8.title": "French-Lithuanian Time's Up Card Creator",
        "projets.w8.org": "French Institute of Lithuania",
        "projets.w8.desc": "Double-sided French-Lithuanian card generator for the Time's Up party game, created for language and cultural workshops.",
        "projets.w3.detail1": "Interactive lessons tailored for A1, A2, and B1 levels.",
        "projets.w3.detail2": "Practice exercises for grammar and conjugation.",
        "projets.w3.detail3": "Built-in dictionary with flashcards for vocabulary acquisition.",
        "projets.w4.detail1": "Geopolitical revision sheets detailed by Indo-Pacific country.",
        "projets.w4.detail2": "Comprehensive glossary of diplomatic and international relations terms.",
        "projets.w4.detail3": "Exam archives and training modules.",
        "projets.w5.detail1": "Local database of 1,949 Kanji, 2,329 vocabulary words, and 218 grammar structures.",
        "projets.w5.detail2": "Integrated text-to-speech for listening to word pronunciation.",
        "projets.w5.detail3": "Learning progress tracking with statistical dashboard.",
        "projets.w5.detail4": "Daily study planner and quiz arena.",
        "projets.w6.detail1": "Interactive alphabet grid with audio pronunciations.",
        "projets.w6.detail2": "Association with transparent words (similar in French and Lithuanian).",
        "projets.w6.detail3": "Designed as an introduction to French at the French Institute.",
        "projets.w7.detail1": "Interactive map of regions and partner institutions.",
        "projets.w7.detail2": "Downloadable resources and guidebooks for teachers.",
        "projets.w7.detail3": "Collaborative space highlighting bilateral school projects.",
        "projets.w8.detail1": "Dynamic generation of bilingual French-Lithuanian game cards.",
        "projets.w8.detail2": "Clean layout optimized for printing double-sided cards.",
        "projets.w8.detail3": "Game rules viewable and printable directly from the platform.",

        "projets.v1.title": "Communication & Visual Design",
        "projets.v1.org": "French Institute of Lithuania",
        "projets.v1.desc": "Graphic design and visual content creation for the social media campaigns and cultural events of the French Institute of Lithuania.",
        "projets.v1.detail1": "Social media visuals for the exhibition \"Écrire en Français\".",
        "projets.v1.detail2": "Social media designs promoting the \"Board Game Evenings\".",
        "projets.v1.detail3": "Visual elements for promoting the \"Francophone Film Week\".",
        "projets.v1.link1": "Exhibition \"Écrire en Français\"",
        "projets.v1.link2": "Board Game Evenings",

        "projets.a1.title": "Climate Fresk Facilitation",
        "projets.a1.org": "Civics & Environment",
        "projets.a1.desc": "Facilitation of collective intelligence workshops to raise awareness about climate change, its causes, and its systemic consequences.",
        "projets.a1.detail1": "Facilitating interactive and collaborative sessions based on IPCC reports.",
        "projets.a1.detail2": "Guiding constructive discussions on individual and collective actions.",
        "projets.a1.detail3": "Adapting outreach and teaching styles for diverse student and citizen groups.",
        "projets.a2.title": "Communication & Event Management",
        "projets.a2.org": "Bordeaux Montaigne University (LEA Association)",
        "projets.a2.desc": "Management of all communications for the LEA student association to enhance student engagement and promote cultural events.",
        "projets.a2.detail1": "Organization of cultural events, conferences, and student meetups.",
        "projets.a2.detail2": "Visual design and active promotion across social media platforms.",
        "projets.a3.title": "Board Game Evenings",
        "projets.a3.org": "French Institute of Lithuania",
        "projets.a3.desc": "Facilitation of multiple board game workshops at the French Institute of Lithuania, promoting playful learning and friendly conversations in French.",
        "projets.a3.detail1": "Selection and presentation of board games tailored for French language learners.",
        "projets.a3.detail2": "Rule explanations and facilitation of conversations in French.",
        "projets.a3.detail3": "Creation of an open space for intercultural exchange and socializing.",
        "projets.a4.title": "French Language Outreach & Promotion",
        "projets.a4.org": "Schools in Lithuania",
        "projets.a4.desc": "Introductory workshops on French language and culture for 5th-grade students (CM1/CM2 equivalent) across several Lithuanian schools, aiming to inspire them to choose French as their second foreign language (LV2).",
        "projets.a4.detail1": "Design of interactive and playful language initiation activities.",
        "projets.a4.detail2": "Dynamic presentations of French culture, geography, and traditions.",
        "projets.a4.detail3": "Outreach efforts to encourage choosing French as a second foreign language.",
        "projets.a5.title": "Student Citizen Convention (CCE)",
        "projets.a5.org": "IEP Fontainebleau / UPEC",
        "projets.a5.desc": "Facilitating roundtables and citizen co-construction workshops during the UPEC Student Citizen Convention at the Fontainebleau Institute of Political Studies.",
        "projets.a5.detail1": "Guiding group debates on policy proposals and ecological transition.",
        "projets.a5.detail2": "Supporting students in drafting official recommendations.",
        "projets.a5.detail3": "Practicing participatory democracy and collective deliberation methods.",
        "projets.a6.title": "SDG & International Solidarity Workshops",
        "projets.a6.org": "La DCC (NGO)",
        "projets.a6.desc": "Facilitating interactive workshops on Sustainable Development Goals (SDGs) and international solidarity during my internship at the DCC.",
        "projets.a6.detail1": "Designing and conducting awareness workshops on SDGs and interculturality.",
        "projets.a6.detail2": "Supporting and training future volunteers on international solidarity issues.",
        "projets.a6.detail3": "Sessions conducted bilingually in French and English.",
        "projets.a7.title": "Intercultural & Integration Workshops",
        "projets.a7.org": "AFS Intercultural Programs",
        "projets.a7.desc": "Facilitation of numerous learning and intercultural workshops for students participating in international school exchanges.",
        "projets.a7.detail1": "Preparing and leading orientation sessions and cultural debriefings.",
        "projets.a7.detail2": "Supporting student integration and helping manage culture shock situations.",
        "projets.a7.detail3": "Workshops led in French, English, and assisted/observed in Japanese.",

        // Parcours
        "parcours.title": "My Journey",
        "parcours.subtitle": "Passionate about geopolitical issues and public policy, I seek to contribute to French initiatives internationally.",
        "parcours.map.title": "🌏 My international journey",
        "parcours.map.france": "France — Studies & Work",
        "parcours.map.japan": "Japan — Exchange & Internship",
        "parcours.map.lithuania": "Lithuania — Currently",
        "parcours.tab.exp": "Experience",
        "parcours.tab.edu": "Education",
        "parcours.tab.skills": "Skills",
        "parcours.tab.lang": "Languages",
        "parcours.exp.heading": "Professional Experience",
        "parcours.exp1.date": "January 2026 — Present",
        "parcours.exp1.title": "Volunteer for Educational and Linguistic Cooperation",
        "parcours.exp1.org": "Institut français de Lituanie",
        "parcours.exp1.d1": "Participation in educational, cultural and civic workshops",
        "parcours.exp1.d2": "Creating visual materials and writing engaging content for social media",
        "parcours.exp1.d3": "Leading French language and Francophone culture discovery workshops",
        "parcours.exp1.d4": "Designing innovative activities combining technology and French culture",
        "parcours.exp2.date": "May 2025 — October 2025",
        "parcours.exp2.title": "International Solidarity Assistant",
        "parcours.exp2.org": "La DCC (NGO)",
        "parcours.exp2.d1": "Managing France Volontaires applications for international solidarity volunteering",
        "parcours.exp2.d2": "Expense report management",
        "parcours.exp2.d3": "Organizing orientations and workshops in partnership with AFD",
        "parcours.exp2.d4": "Administrative follow-up of volunteer files (Visa, residence permit, insurance…)",
        "parcours.exp3.date": "January 2024 — January 2025",
        "parcours.exp3.title": "International Programs Assistant",
        "parcours.exp3.d1": "Transport administration (flights, trains), logistics",
        "parcours.exp3.d2": "Administrative file management (visas, applications)",
        "parcours.exp3.d3": "English-French-Japanese translation",
        "parcours.exp3.d4": "Social media management (Meta, Instagram)",
        "parcours.edu.heading": "Academic Education",
        "parcours.edu1.date": "August 2023 — November 2025",
        "parcours.edu1.title": "Master in European and International Studies",
        "parcours.edu1.org": "Institut d'Études Politiques (Sciences Po)",
        "parcours.edu1.desc": "Advanced training in international relations, European policy and international cooperation. Master fully taught in English.",
        "parcours.edu2.date": "September 2020 — June 2023",
        "parcours.edu2.title": "Bachelor in Applied Foreign Languages",
        "parcours.edu2.org": "Bordeaux Montaigne University",
        "parcours.edu2.desc": "English-Japanese specialization with strong components in international relations and intercultural communication.",
        "parcours.edu3.date": "March 2018 — February 2019",
        "parcours.edu3.title": "High School Exchange — AFS Program",
        "parcours.edu3.desc": "Year-long cultural and linguistic exchange in Japan. Full immersion in Japanese culture and intensive language learning.",
        "parcours.edu4.date": "June 2017 — July 2020",
        "parcours.edu4.title": "Baccalauréat STI2D",
        "parcours.edu4.org": "Lycée Albert Claveille",
        "parcours.edu4.desc": "Science and Technology for Industry and Sustainable Development.",
        "parcours.skills.heading": "Technical Skills",
        "parcours.skill1.sub": "Full office suite",
        "parcours.skill4.sub": "Website creation & management",
        "parcours.skill5.sub": "Graphic design & social media",
        "parcours.skill6.sub": "Video editing & production",
        "parcours.interests.heading": "Interests",
        "parcours.int1": "IT & Technology",
        "parcours.int2": "Badminton",
        "parcours.int3": "Photography",
        "parcours.int4": "Geopolitics",
        "parcours.lang.heading": "Language Skills",
        "parcours.lang1.name": "French",
        "parcours.lang1.level": "Native language",
        "parcours.lang1.label": "Native",
        "parcours.lang2.name": "English",
        "parcours.lang2.level": "Professional proficiency",
        "parcours.lang2.label": "C1 Advanced — Master in English",
        "parcours.lang3.name": "Japanese",
        "parcours.lang3.level": "Professional proficiency",

        // Admin
        "admin.title": "Admin Dashboard"
    }
};

let currentLang = localStorage.getItem('i18n_lang') || 'fr';

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            // Check if placeholder
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                if (el.placeholder) el.placeholder = translations[currentLang][key];
            } else {
                el.innerText = translations[currentLang][key];
            }
        }
    });

    // Handle data-i18n-html attributes (for elements with mixed content like icons)
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const key = el.getAttribute('data-i18n-html');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    const langBtn = document.getElementById('lang-btn');
    if (langBtn) {
        langBtn.innerText = currentLang === 'fr' ? 'EN' : 'FR';
    }
}

function toggleLanguage() {
    currentLang = currentLang === 'fr' ? 'en' : 'fr';
    localStorage.setItem('i18n_lang', currentLang);
    applyTranslations();
}

// Init on load
document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();

    // Highlight active link
    const path = window.location.pathname.split('/').pop() || 'index.html';
    document.querySelectorAll('.nav-links a').forEach(link => {
        if (link.getAttribute('href') === path) {
            link.classList.add('active');
        }
    });
});
